
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - pulumi-controller.example.com
  resources:
  - iamaccounts
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - pulumi-controller.example.com
  resources:
  - iamaccounts/finalizers
  verbs:
  - update
- apiGroups:
  - pulumi-controller.example.com
  resources:
  - iamaccounts/status
  verbs:
  - get
  - patch
  - update
